language: python
sudo: false
cache:
  - pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  matrix:
    - DJANGO="Django<1.9,>=1.8"
    - DJANGO="Django<1.10,>=1.9"
    - DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
matrix:
  allow_failures:
    - env: DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
install:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - pip install $DJANGO
script:
  - flake8 --jobs=2 .
  - py.test
