language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - DJANGO="<1.6,>=1.5"
  - DJANGO="<1.7,>=1.6"
  - DJANGO="<1.8,>=1.7"
  - DJANGO="<1.9,>=1.8"

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="<1.8,>=1.7"
    - python: "2.6"
      env: DJANGO="<1.8,>=1.7"
install:
  - pip install --upgrade pip
  - pip install .
  - pip install Django$DJANGO
  - pip install pytest pytest-pep8 pytest-flakes django-pytest --use-mirrors
script:
  - python setup.py test
